version: "3"

services:
  master:
    image: tempex/master
    build:
      context: ..
      dockerfile: docker/master/Dockerfile

  base_service: &base
    image: tempex/master
    depends_on:
      - master
    volumes:
      - "$TEMPEX_PACKAGE_ROOT:/app/tempex"
      - "$TEMPEX_CONFIG_FILE:/app/config.ini"
      - "$PWD:$PWD"
    environment:
      TEMPEX_STORAGE_ROOT: "$PWD"
    working_dir: "/app"
    entrypoint: "python3 -u -m tempex"
    command: "--version"

  collector:
    <<: *base
    command: "collector"
    network_mode: "host"
