version: "3"

services:
  master:
    image: tempex/master
    build:
      context: ..
      dockerfile: docker/master/Dockerfile

  base_service: &base
    image: tempex/master
    depends_on:
      - master
    volumes:
      - "$TEMPEX_PACKAGE_ROOT:/app/tempex"
      - "$TEMPEX_CONFIG_FILE:/app/config.ini"
    environment:
      TEMPEX_STORAGE_ROOT: "$PWD"
    working_dir: "/app"
    entrypoint: "python3 -u -m tempex"
    command: "--version"

  collector:
    <<: *base
    command: "collector"
    network_mode: "host"

  proxy:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - "$TEMPEX_PACKAGE_ROOT/tempex/frontend:/var/www"
      - "$TEMPEX_PACKAGE_ROOT/docker/proxy/nginx.conf:/etc/nginx/conf.d/default.conf.template"


