version: "3"

services:
  master:
    image: tempex/master
    build:
      context: ..
      dockerfile: docker/master/Dockerfile

  base_service: &base
    image: tempex/master
    depends_on:
      - master
    volumes:
      - "$TEMPEX_PACKAGE_ROOT:/app/tempex"
      - "$TEMPEX_CONFIG_FILE:/app/config.ini"
      - "$PWD:$PWD"
    environment:
      TEMPEX_STORAGE_ROOT: "$PWD"
    working_dir: "/app"
    entrypoint: "python3 -u -m tempex"
    command: "--version"

  collector:
    <<: *base
    #command: "collector"
    network_mode: "host"

  api_service:
    <<: *base
    entrypoint: "/usr/bin/env uwsgi"
    command: "--socket 0.0.0.0:3031 --module tempex.api.app"
    expose:
      - "3031"

  proxy:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - "$TEMPEX_PACKAGE_ROOT/frontend:/var/www"
      - "$TEMPEX_PACKAGE_ROOT/docker/proxy/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - api_service
      

